"""add file_path to Data

Revision ID: 3856d7beee6e
Revises: c10c5af597fd
Create Date: 2024-08-23 10:21:25.546003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3856d7beee6e'
down_revision = 'c10c5af597fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
